### ISSUE TITLE
Production ready module

### ISSUE THREAD

**Issue by diegoaguilar** [IonicaBizau/node-cobol#1]
Hello, more than an _issue_ I guess this is a doubt. What makes this **production ready**?

**Comment by IonicaBizau** [comment]
Stability and fun! :stuck_out_tongue_winking_eye:

**Comment by diegoaguilar** [comment]
What are the conditions to claim for its stability?

**Comment by IonicaBizau** [comment]
If you like it, use it. If you have any issues with it, just let me know, lol. :smile:

**Comment by IonicaBizau** [comment]
And btw, just found [this article](http://www.zdnet.com/article/50-years-and-still-going-strong-will-we-ever-be-ready-to-kill-off-cobol/). Interesting read! Accidentally, written by Romanians about Romanians. :laughing:

> Catalin Cosoi, chief security strategist at Bitdefender, told ZDNet that there are very few vulnerabilities involving the language. "COBOL wasn't designed with a security mindset. However, considering that it's used in finance and in state-owned organizations, a natural security-by-obscurity system emerged," he said.

...and

>  A 2012 survey found that 48 percent of businesses and government organizations rely heavily on COBOL, compared to JavaScript's 41 percent, Java on 39 percent, and C# on 26 percent. What's more, over one-third of those surveyed said they planned to develop new applications in COBOL in the future.

Funny and probably true! :smile:
