### ISSUE TITLE
Adding another article

### ISSUE THREAD

**Issue by aln787** [IonicaBizau/node-cobol#10]
Your repo is mentioned by another article: [3 open source projects for modern COBOL development](http://opensource.com/life/15/10/open-source-cobol-development) on [OpenSource.com](http://opensource.com/) by [Joshua Allen Holm](http://opensource.com/users/holmja)

**Comment by IonicaBizau** [comment]
@aln787 Ohh, nice! Thanks! Can you please [add it for me](https://github.com/IonicaBizau/node-cobol/blob/5f61b261957ff3a1431653995d4464c722edd67d/.blah/README.ejs#L77)? :smile:

**Comment by aln787** [comment]
@IonicaBizau I submitted a PR adding it.

**Comment by IonicaBizau** [comment]
@aln787 Thanks, I pulled from your fork directly since the pull request was opened inside of your fork. :smile: 

:ship: `1.3.1` :tada:
