### ISSUE TITLE
Ability to run dynamically generated COBOL code / use a variable instead of comment

### ISSUE THREAD

**Issue by Marak** [IonicaBizau/node-cobol#27]
Hello. Neat project!

Ran into a minor issue.

Is it possible to pass a COBOL script variable as a string into the compiler instead of having to use comments inside the JavaScript function? Not looking to run from a file, looking to pass in COBOL code as a dynamically created string.

Thanks!

**Comment by IonicaBizau** [comment]
I think that's already supported. I didn't try this, but I expect it to work:

``` js
// Dependencies
var Cobol = require("cobol");

// Execute some COBOL snippets
Cobol(`
                   IDENTIFICATION DIVISION.
                   PROGRAM-ID. HELLO.
                   ENVIRONMENT DIVISION.
                   DATA DIVISION.
                   PROCEDURE DIVISION.
                   PROGRAM-BEGIN.
                   DISPLAY "Hello world".
                   PROGRAM-DONE.
                   STOP RUN.
`, function (err, data) {
    console.log(err || data);
});
// => "Hello World"
```

**Comment by Marak** [comment]
Confirmed, thank you!

I should have read the README a bit closer.
