### ISSUE TITLE
RM/Cobol

### ISSUE THREAD

**Issue by Kaffiend** [IonicaBizau/node-cobol#29]
Has this been tested with Microfocus RM/Cobol?

**Comment by IonicaBizau** [comment]
I only used it with Open/GNU COBOL.

**Comment by Kaffiend** [comment]
We currently use a C# library that wraps VanGui, this would be an awesome alternative if it works.

**Comment by Kaffiend** [comment]
im curious if this could be ported over for RM/Cobol.

**Comment by IonicaBizau** [comment]
How do you compile a file using RM/Cobol? Is there a cli interface?

**Comment by Kaffiend** [comment]
Yes, there is. There is also already some interoperability that may be useful.
https://www.microfocus.com/media/data-sheet/rmcobol-data-sheet_tcm6-3843.pdf

**Comment by IonicaBizau** [comment]
I never used it, but as long you can call it as a command, we should be able to run the specific command for it from the Node.js side.

Basically here we have to change it, in that case (maybe with an option): https://github.com/IonicaBizau/node-cobol/blob/6a130b35f4d4f9f484676e1b8d5a9a657bc6a50d/lib/compile/index.js#L60-L62

**Comment by Kaffiend** [comment]
interesting, actually could just create an environment var or something to map `cobc` as `rmcobol`

**Comment by Kaffiend** [comment]
my curiosity is peaked, im trying to wrap my head around getting data back to node, i understand getting it in with SYSIN. By this i mean run a program with input parameters, read an `.inx` and get that data/collection back to node.

**Comment by IonicaBizau** [comment]
@Kaffiend That's correct, you can alias `cobc` to something else and it will just work.

Currently sending data back is done using the stdout stream... I do agree that there should be a better way to do it, but that was my quick implementation. :grin: 

See this example: https://github.com/IonicaBizau/node-cobol/blob/6a130b35f4d4f9f484676e1b8d5a9a657bc6a50d/examples/index.js#L22-L27

**Comment by Kaffiend** [comment]
The way we do it is actually pretty decent with Van Gui.
```
CALL "VG$NEWARRAY" USING VG-RECORD.
PERFORM 322-READ-START THRU 322-EXIT.
CALL "VG$SETVALUE" USING ELEMENT, VG-RECORD.
```
the `SETVALUE` triggers a delegate on the calling side and we parse out the data in the arrays.

**Comment by Kaffiend** [comment]
By the way, i figured i'd update you, on some things i've been working on. I've ported this over for Microfocus RM/COBOL. I've found a use case to feed my customer's data to a centralized data repository effectively syncing my cobol backend at my customer sites with my mongo backend api for web services.
