### ISSUE TITLE
Add type definitions

### ISSUE THREAD

**Issue by frankcai** [IonicaBizau/node-cobol#30]
Please add type definitions for this module.
Example for node: https://www.npmjs.com/package/@types/node

**Comment by IonicaBizau** [comment]
@fc89 Thanks for that. I'm not sure what this means, tho. Can you explain how this is useful? I'm not that much into TypeScript.

**Comment by frankcai** [comment]
Without it, anyone using TypeScript can't call your module without workarounds. You could use https://github.com/DefinitelyTyped/DefinitelyTyped to publish one.

**Comment by IonicaBizau** [comment]
I can't do this right now, but contributions are welcome! Thanks!

**Comment by frankcai** [comment]
I was mistaken. The definitions enable intellisense but are otherwise not needed.
