### ISSUE TITLE
Running COBOL in serverless

### ISSUE THREAD

**Issue by kostrse** [IonicaBizau/node-cobol#33]
Unfortunately, dependency on **GnuCOBOL** prevents utilizing it in serverless environments (FaaS).

Would be awesome to hear if someone comes up with idea how to achieve that 😸

**Comment by IonicaBizau** [comment]
That would be nice, indeed! /cc #5

**Comment by tjwebb** [comment]
@kostrse @IonicaBizau We got this working on OpenWhisk: https://github.com/morecobol/cobol.run

**Comment by IonicaBizau** [comment]
That's amazing, @tjwebb! :sparkles:
