### ISSUE TITLE
Why??

### ISSUE THREAD

**Issue by dandv** [IonicaBizau/node-cobol#34]

**Comment by IonicaBizau** [comment]
I thought it should be interesting to link two technologies: an old one (COBOL) and a recent one (Node.js).

Few years ago my brother gave me a book about COBOL. I played a little bit with COBOL programs and I wanted to combine it with Node.js.

Also, deep in my mind, I had a small though that this would produce a little bit of buzz in the programming world, and it did—even more than I expected. 😁
