### ISSUE TITLE
Arbitrary compiler options

### ISSUE THREAD

**Issue by B14m3m3** [IonicaBizau/node-cobol#39]
Currently only the free flag can be set with the options.
Why not let arbitrary options to be set, like adding libraries with `-l<lib>` or other cobc compiler specific options?

Simple fix i would propose is to change 
```js 
if (options.free) {
      args.free = options.free;
}
```
to
```js
Object.assign(args, options);
```
This allows the user to add any compiler options they would want. Also overwriting the existing arguments in the args object if the user wants.

**Comment by IonicaBizau** [comment]
I agree! :+1:
