### ISSUE TITLE
Grandpa?

### ISSUE THREAD

**Issue by Toltar** [IonicaBizau/node-cobol#6]
What are you doing in nodejs? ;p jk

**Comment by IonicaBizau** [comment]
Obviously, COBOL, right? :laughing: 

Well, I am a Node.js developer and I write little modules which are used in bigger modules which are used in bigger projects. :smile: 

It was interesting to develop this project and see that people like it, actually. :dizzy:
And btw, I am 19. :hourglass:

**Comment by scshepard** [comment]
A few years ago, there were more lines of Internet Commerce code written in Cobol then in another language. Pretty fly for an old guy!

Date: Thu, 20 Aug 2015 22:32:10 -0700

**Comment by scshepard** [comment]
Whoops! Cobol was written by Rear Admiral Grace Hopper. So, show some respect you "punk" kids:
http://www.i-programmer.info/history/people/294-the-mother-of-cobol.html

From: sc_shepard@hotmail.com
To: reply@reply.github.com
Subject: RE: [node-cobol] Grandpa? (#6)
Date: Fri, 21 Aug 2015 05:33:37 +0000

A few years ago, there were more lines of Internet Commerce code written in Cobol then in another language. Pretty fly for an old guy!

Date: Thu, 20 Aug 2015 22:32:10 -0700

**Comment by IonicaBizau** [comment]
@scshepard Indeed! We need more people like Rear Admiral Grace Hopper.

**Comment by scshepard** [comment]
She is a brilliant lady; What does one Nanosecond look like?https://www.youtube.com/watch?v=JEpsKnWZrJ8

Date: Thu, 20 Aug 2015 22:37:12 -0700

**Comment by lcristianiim** [comment]
Ionica Bizau, your modesty and respect for all people can be a model. I remember the first time I've ever heard of briliant Rear Admiral Grace Hopper. You spoked of her and cobol with great admiration and respect. Yes you are young but also very talented and modest. Keep up the good will and good work and maybe more people like Rear Admiral Grece Hopper will appear in time.
Thank you @IonicaBizau

**Comment by IonicaBizau** [comment]
@scshepard That video is :sparkles: 

@lcristianiim Thanks for the kind words. :blush:

**Comment by IonicaBizau** [comment]
Guys, just found this!

[![image](https://cloud.githubusercontent.com/assets/2864371/9405470/987e4506-4800-11e5-9027-29ada784c7fa.png)](https://github.com/search/advanced)

**Comment by Toltar** [comment]
@IonicaBizau Lol its not a bad idea at all. At least we dont have another JS framework :+1: Kudos to you sir for coming up with something original.

**Comment by IonicaBizau** [comment]
> At least we dont have another JS framework

Ohhh, yeah! :smile: Really don't like these monolithic js frameworks from the 21st century. :tokyo_tower: 

Thanks! :sparkles:
