### ISSUE TITLE
Support for promises

### ISSUE THREAD

**Issue by krzkaczor** [IonicaBizau/node-cobol#7]
Hi guys!
I am working on translator from Cobol to C# (written in JS :D)  and I use node-cobol to do validation tests etc. Almost first thing that I have done was writing small promise enabling wrapper around it. 

What do you think about introducing promises to node-cobol? I think that we could introduce it similar to jquery ajax promises - if there's no callback given, return promise. So it won't break current API.

What do you think about that idea?

**Comment by krzkaczor** [comment]
I got it working on my fork it looks like this:

``` javascript
var Q = require('q');
var helloWorld1 = Cobol(function () { /*
       IDENTIFICATION DIVISION.
       PROGRAM-ID. HELLO.
       PROCEDURE DIVISION.

       PROGRAM-BEGIN.
       DISPLAY "Hello world".

       PROGRAM-DONE.
       STOP RUN.
 */ });

var helloWorld2 = Cobol(function () { /*
       IDENTIFICATION DIVISION.
       PROGRAM-ID. HELLO.
       PROCEDURE DIVISION.

       PROGRAM-BEGIN.
       DISPLAY "Hello world second time!".

       PROGRAM-DONE.
       STOP RUN.
 */ });

Q.all([helloWorld1, helloWorld2]).then(function (res) {
 console.log(res);
}).catch(function(err) {
 console.log(err);
});
```

link here: https://github.com/krzkaczor/node-cobol

**Comment by IonicaBizau** [comment]
Hey @krzkaczor! 

> I am working on translator from Cobol to C# (written in JS :D) and I use node-cobol to do validation tests etc.

Oh, that's :cool:! 

> What do you think about introducing promises to node-cobol? 

Honestly, I never liked promises... however, if you lazy-load them (I see you're using the `q` library), I don't have anything against–probably other like it. So, I'd say to only `require` the `q` library when it's needed, _then_ you can create a pull request. :sparkles:

**Comment by krzkaczor** [comment]
I think that there's no way to lazy load Q module as in my fork I always return promise. If you don't want to use it - just pass callback and forget about that promise. It mimics jquery ajax implementation. I have added a little bit of documentation and created MR.

**Comment by IonicaBizau** [comment]
As we already discussed in #8, I merged your changes in a new library–could you please create a pull request to let the people know there is such a thing too? :smile: 

Edit the `.blah/README.ejs` file and then the `README.md` will got updated by running `blah -r`. :sparkle:

**Comment by krzkaczor** [comment]
Thanks, great work man ;) I will just delete my fork - there is no reason to keep it

**Comment by IonicaBizau** [comment]
@krzkaczor Yep, your commits are already in the [main project](https://github.com/IonicaBizau/node-cobol-promises/commits?author=krzkaczor). :four_leaf_clover:
